import struct
import xml.etree.ElementTree as ET
from pathlib import Path


def test_brand_asset_directories_exist():
    assert Path("docs/assets/brand").is_dir()
    assert Path("docs/assets/screenshots").is_dir()


def test_legacy_root_images_are_removed():
    assert not Path("nanoserver.png").exists()
    assert not Path("social_preview.png").exists()


def test_master_icon_svg_exists_and_has_expected_viewbox():
    svg_path = Path("docs/assets/brand/fesium-orbit.svg")
    assert svg_path.exists()

    root = ET.fromstring(svg_path.read_text(encoding="utf-8"))
    assert root.tag.endswith("svg")
    assert root.attrib["viewBox"] == "0 0 512 512"


def read_png_dimensions(path: Path) -> tuple[int, int]:
    with path.open("rb") as handle:
        signature = handle.read(8)
        assert signature == b"\x89PNG\r\n\x1a\n"
        length = struct.unpack(">I", handle.read(4))[0]
        assert length == 13
        chunk = handle.read(4)
        assert chunk == b"IHDR"
        width = struct.unpack(">I", handle.read(4))[0]
        height = struct.unpack(">I", handle.read(4))[0]
        return width, height


def test_social_preview_png_matches_github_recommendation():
    png_path = Path("docs/assets/brand/fesium-social-preview.png")
    assert png_path.exists()
    assert png_path.stat().st_size < 1_000_000
    assert read_png_dimensions(png_path) == (1280, 640)


def mean_luminance(path: Path) -> int:
    """Rough average brightness of a PNG, 0-255, without an image library.

    Decodes the pixels with zlib and the PNG filter rules. The suite runs on
    the runtime dependencies alone, and this is the one number that says
    whether a card reads as light or dark.
    """
    import struct
    import zlib

    data = path.read_bytes()
    header = data.index(b"IHDR") + 4
    width, height, depth, colour = struct.unpack(">IIBB", data[header:header + 10])
    assert (depth, colour) == (8, 2), f"expected 8-bit RGB, got depth={depth} colour={colour}"

    raw, index = bytearray(), 8
    while index < len(data):
        length, kind = struct.unpack(">I", data[index:index + 4])[0], data[index + 4:index + 8]
        if kind == b"IDAT":
            raw += data[index + 8:index + 8 + length]
        index += 12 + length
    pixels = zlib.decompress(bytes(raw))

    stride, previous, total = width * 3, bytearray(width * 3), 0
    at = 0
    for _ in range(height):
        filter_type, at = pixels[at], at + 1
        line = bytearray(pixels[at:at + stride])
        at += stride
        for i in range(stride):
            left = line[i - 3] if i >= 3 else 0
            up = previous[i]
            if filter_type == 1:
                line[i] = (line[i] + left) & 0xFF
            elif filter_type == 2:
                line[i] = (line[i] + up) & 0xFF
            elif filter_type == 3:
                line[i] = (line[i] + (left + up) // 2) & 0xFF
            elif filter_type == 4:
                upper_left = previous[i - 3] if i >= 3 else 0
                estimate = left + up - upper_left
                candidates = (abs(estimate - left), abs(estimate - up),
                              abs(estimate - upper_left))
                nearest = (left, up, upper_left)[candidates.index(min(candidates))]
                line[i] = (line[i] + nearest) & 0xFF
        total += sum(line)
        previous = line
    return round(total / (width * height * 3))


def test_the_social_previews_are_a_light_and_dark_pair():
    """Two cards, and genuinely different ones.

    The card before these baked the app's dark ground in and measured 29/255,
    so GitHub rendered it as a black rectangle. The light card is what GitHub
    is pointed at; the dark one is for a light surface. Asserting only that
    both files exist would pass if the generator emitted the same image twice,
    which is exactly what a copy-pasted palette would do.
    """
    light = Path("docs/assets/brand/fesium-social-preview.png")
    dark = Path("docs/assets/brand/fesium-social-preview-dark.png")

    assert read_png_dimensions(dark) == (1280, 640)
    assert dark.stat().st_size < 1_000_000

    light_mean, dark_mean = mean_luminance(light), mean_luminance(dark)
    assert light_mean > 200, f"the light card reads dark at {light_mean}/255"
    assert dark_mean < 60, f"the dark card reads light at {dark_mean}/255"


def test_brand_assets_have_a_generator():
    """The script is the source of truth, not a hand-edited SVG beside the PNG.

    The old preview shipped a .svg alongside the .png and the two drifted - the
    PNG was regenerated by hand and the vector kept the pre-matte palette.
    One generator produces every asset from a single geometry definition.
    """
    assert Path("scripts/build_brand.py").exists()
    assert Path("docs/assets/brand/fesium-banner.png").exists()
    assert not Path("docs/assets/brand/fesium-social-preview.svg").exists()


def test_readme_uses_new_brand_assets_and_repo_slug():
    readme = Path("README.md").read_text(encoding="utf-8")
    assert "docs/assets/brand/fesium-banner.png" in readme
    assert "https://github.com/goAuD/Fesium.git" in readme
    assert "cd Fesium" in readme
    assert "nanoserver.png" not in readme
    assert "social_preview.png" not in readme
    assert "NanoServer/" not in readme


def test_roadmap_uses_fesium_name():
    roadmap = Path("ROADMAP.md").read_text(encoding="utf-8")
    assert roadmap.startswith("# Fesium Roadmap")
    assert "NanoServer" not in roadmap


def test_legacy_design_system_doc_is_removed():
    assert not Path("DESIGN_SYSTEM.md").exists()
